# @package _group_
- _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: '.'
  name: ''
  version: 'lightning_logs'
- _target_: pytorch_lightning.loggers.MLFlowLogger
  experiment_name: ${experiment_name}
  tracking_uri: 'file:/workspace/mlruns'
  tags: ~
  save_dir: ~
