# @package _group_
- _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: '.'
  name: ''
  version: 'lightning_logs'
- _target_: pytorch_lightning.loggers.MLFlowLogger
  experiment_name: ${experiment_name}
  tracking_uri: 'file:/workspace/mlruns'
  tags: ~
  save_dir: ~
- _target_: pytorch_lightning.loggers.NeptuneLogger
  api_key: ${env:NEPTUNE_API_TOKEN}
  project_name: kanda/${project_name}
  experiment_name: ${experiment_name}
  tags: ~
  upload_source_files: [/workspace/src, /workspace/config]
