defaults:
  - data: AdobeFont
  - trainer: basic
  - callbacks: basic
  - loggers: basic

project_name: PatchSets
experiment_name: Default

debug: False

hparams:
  patch_size: 15
  hidden_n: 1024
  output_n: ${data.class_num}
  pool_mode: max
  patch_num_min: 1
  patch_num_max: 256
  seed: 0
  batch_size: 256
  num_workers: 6
  max_epochs: 10000
  min_epochs: 10
  patience: 50
  optimizer: Adam
  lr: 0
  data_split_num: ${data.datamodule.data_split_num}
  data_use_num: ${data.datamodule.data_use_num}

hydra:
  run:
    dir: ./outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
