dataset:
  class: src.dataset.adobe_font_char_images
  params:
    root: '/dataset/'
transform:
  - class: torchvision.transforms.ToTensor
target_transform:
  - class: src.dataset.ExtractAlphabet
dataset_output_n: 52
