dataset:
  class: src.dataset.AdobeFontCharImages
  params:
    root: '/dataset/'
train_transform:
  - class: torchvision.transforms.ToTensor
train_target_transform: ~
test_transform:
  - class: torchvision.transforms.ToTensor
test_target_transform: ~
